### ISSUE TITLE
Filtering on mobile devices: let the user add more than one filter at once

### ISSUE THREAD

**Issue by rhfamme** [Shopify/dawn#1311]
When you are using your phone and want to use the filter function and you press on one of the filters you automatically exit the list which gives more unnecessary work for the user if they want to use more than one filter. I want the user to be able to add more filters without leaving the filter list.

One solution would be for the user to press a "use" button to exit the filter list instead of being automatically taken away from the list when they are choosing one filter

![IMG_6063 2](https://user-images.githubusercontent.com/99011309/152504146-91d0e550-396c-4146-a8b9-fef1f9ff708a.jpg)

**Comment by melissaperreault** [comment]
Hey @rhfamme, thanks for the feedback! Just making sure you are aware, it is possible to go back to the filter list to add more filters from additional categories by taping [this back link](https://screenshot.click/22-02-anp7v-nth53.png), while keeping the drawer open.

Otherwise, users that would only want to filter from one category would require 2 steps to apply the filters which wouldn't be ideal experience.

**Comment by gregjotau** [comment]
@rhfamme we can close this as there is another issue fixing this.
