### ISSUE TITLE
[Header] Empty link present by default

### ISSUE THREAD

**Issue by svinkle** [Shopify/dawn#1461]
## Issue summary

The header cart notification features a link with no text.

Discovered while running [WAVE Evaluation Tool](https://chrome.google.com/webstore/detail/wave-evaluation-tool/jbbplnpkjmmeebjpijfedlgcdilocofh).

#### HTML

```html
<a
  href="/cart"
  id="cart-notification-button"
  class="button button--secondary button--full-width"
></a>
```

## Steps to reproduce

1. Go to any Dawn demo store with any supported browser
2. Run the [WAVE Evaluation Tool](https://chrome.google.com/webstore/detail/wave-evaluation-tool/jbbplnpkjmmeebjpijfedlgcdilocofh) and review the Errors tab

### Expected

- Links to have an accessible name by default.

### Actual

- Cart notification features empty link.

## Recommendation

Set an accessible name by default. When a product is added to the cart, update with the total count as expected.

#### HTML

```html
<!-- Default, hidden state: -->
<a
  href="/cart"
  id="cart-notification-button"
  class="button button--secondary button--full-width"
>
  View my cart
</a>

<!-- Cart count state: -->
<a
  href="/cart"
  id="cart-notification-button"
  class="button button--secondary button--full-width"
>
  View my cart (1)
</a>
```

<!-- #### Diff

```diff
- line removed
+ line added
``` -->

## Specifications

- **Dawn version:** 3.0
- **Browser:** Any
- **Component:** Header
- **WCAG Principal:** Perceivable
- **WCAG SC:** [1.3.1: Info and Relationships](https://www.w3.org/WAI/WCAG21/Understanding/info-and-relationships.html)
- **Severity:** Low
- **Effort:** Low

**Comment by sofiamatulis** [comment]
**Some more context:**

This is not an issue once you add something to the cart and re-run the tool:
https://screenshot.click/10-56-2pl7p-3ccfw.png

However it is an issue before you add something to the cart
https://screenshot.click/10-18-atoo0-e9hxo.png

This is because the content hasn't been added/updated by the API. Ideally we can have some default text like "View my cart: without the total numbers and let the API update that.

This way we don't run into this issue
