### ISSUE TITLE
[Collapsible content] Add padding-bottom to collapsible row blocks 

### ISSUE THREAD

**Issue by melissaperreault** [Shopify/dawn#1597]
### Observation

- [ ] Add `padding-bottom: 1.5rem;` to `Collapsible row` blocks to [have more breathing room for the layout](https://screenshot.click/22-04-anpvj-epasg.png) `Row container` all around. ([After reference](https://screenshot.click/22-04-ebzg0-gc3oi.png))

**Comment by LucasLacerdaUX** [comment]
@melissaperreault 
Just to confirm: do we want to add only the `padding-bottom` or should we apply it to both `top` and `bottom`?

Asking because an `1.5rem` padding to the element makes the spacing looks uneven spacing when hovering. Is this what we want? See examples below.

## Current
### Normal
<img width="654" alt="image" src="https://user-images.githubusercontent.com/37168033/165624687-547548fd-ad48-4dc7-b9dd-57a09efcbf39.png">

### Hover
<img width="654" alt="image" src="https://user-images.githubusercontent.com/37168033/165624665-da9e24cf-572d-462e-81c8-3e0e22bcf647.png">

## `padding-bottom: 1.5rem`
### Normal
<img width="654" alt="image" src="https://user-images.githubusercontent.com/37168033/165624771-1dacb948-8c37-44a5-a748-b7584d703504.png">

### Hover
<img width="654" alt="image" src="https://user-images.githubusercontent.com/37168033/165624797-6eae4f15-c6f0-40ce-bd11-5be79ed89d4a.png">

## `padding-bottom: 1.5rem` && ## `padding-top: 1.5rem`
### Normal
<img width="654" alt="image" src="https://user-images.githubusercontent.com/37168033/165624884-0f9df9fa-9b27-429f-968a-4d3b2433a8e4.png">

### Hover
<img width="654" alt="image" src="https://user-images.githubusercontent.com/37168033/165624904-ebec6e91-4168-4c72-93d8-d36c006723f1.png">
