### ISSUE TITLE
[v1.1.0] Appears to have broken "live color picking" within the Editor

### ISSUE THREAD

**Issue by beefchimi** [Shopify/dawn#201]
**Describe the current behavior**

@theresa-paul recorded this video of her using the latest Dawn `v1.1.0`: https://videobin.shopify.io/v/1zk5p

As you can see, the `Preview` colors are not updating upon selection of a new swatch. Both Theresa and I tested against some other themes and could not recreate this issue. Theresa tested against the previous Dawn release and was also unable to recreate the issue. It would seem that this problem is isolated to the `v1.1.0` version.

**Describe the expected behavior**

Upon selecting a new color from the `Theme settings > colors` Panel, we should see that new color reflected within the `Preview` right away.

Looking at the DOM, the Online Store Editor > ColorPicker generates a `CSS custom property` name that is not the same as what the Dawn theme code is using:

![Screen Shot 2021-07-15 at 4 35 54 PM](https://user-images.githubusercontent.com/643944/125856112-8b7a0b79-7e98-4493-ace5-55a4d9596d89.png)

**Version information (Dawn, browsers and operating systems)**
- Dawn Version: 1.1.0
- Chrome Version: 91.0.4472.114 (Official Build) (x86_64)
- macOS Version: 11.4

**Possible solution**

Not sure, but I plucked these two PRs that may have relevant code changes:
- https://github.com/Shopify/dawn/pull/83
- https://github.com/Shopify/dawn/pull/97

**Comment by KaichenWang** [comment]
Yes, I can confirm the following

### Changes made - https://github.com/Shopify/dawn/pull/83
#### Before
```
--color-base-text-rgb: {{ settings.colors_text | color_to_rgb | remove: 'rgb(' | remove: ')' }};
```

#### After
```
--color-base-text-rgb: {{ settings.colors_text.red }}, {{ settings.colors_text.green }}, {{ settings.colors_text.blue }};
```

### Reason
- Avoid "hacky" `remove: 'rgb(' | remove: ')'` filters
- Allows for simplification of Dawn CSS
- Fix invalid CSS if the color is set to `none`

### Side-effect
RGB colors defined using ColorDrop `red`, `green` and `blue` properties do not update in the editor until saved.

### Next steps
Who could I coordinate with on the Editor side to address this, because moving forward I think using `red`, `green` and `blue` properties is better than the previous approach in themes.
