### ISSUE TITLE
[Header] Mega menu shadow on top of header

### ISSUE THREAD

**Issue by ludoboludo** [Shopify/dawn#2067]
**Describe the current behavior**

If you're setting a vertical top shadow on the popup and have mega menu enabled, the shadow will be on top of the header

**Describe the expected behavior**

The vertical top shadow should be going under the header/hidden

**Version information (Dawn, browsers and operating systems)**
- Dawn Version: 7.0.0

**Possible solution**
Look into using some pseudo elements like done for other components

**Additional context/screenshots**
![](https://screenshot.click/25-25-l0skm-9akkv.png)

**Comment by kmeleta** [comment]
A global-popup-settings class was added for the nav, but it currently just uses box-shadow and z-index: -1 directly. We should update this to follow the same pattern we use for global cards, media, content containers, etc where the shadow styles are added onto a ::after pseudo element with a z-index: -1 on that instead. This _should_ solve this bug, 

However it would also be nice to update other uses of the global popup styles to use this same class. With a quick glance, it appears these elements are using these styles directly instead of the global class.
- facets
- predictive search
- disclosure (footer?)
- product popup block
