### ISSUE TITLE
Image Banner Updates

### ISSUE THREAD

**Issue by valeriegohier** [Shopify/dawn#216]
We explored the current UI of ''Image banner'' to see how it could be improved to look more sophisticated. 

Issues we found 
- The call to action being a bit big, bulky and square.
- The text box being very square and covering a lot of the images behind it on larger screens
- The amount of white space between ''Header'' and ''Text''

Short and sweet example: 
![Screen Shot 2021-07-15 at 1 19 52 PM](https://user-images.githubusercontent.com/53573494/126083925-b1701d55-34ba-4fff-be6c-481ca59bd39d.png)

Longer example: 
![image](https://user-images.githubusercontent.com/8127145/126565627-6a3c27b4-a95e-4129-be34-c166b5a6886d.png)

------

### Proposed solutions: 

- [ ] See Olivia's comment for updates to max and min width, and spacing between elements. 
- [ ] Introduce a setting to remove the color background of the text box to achieve a look similar to screenshot below, which is more aligned of modern / trendy e-commerce shops, and likely more aligned with merchants desired looks and feels: 

![image](https://user-images.githubusercontent.com/8127145/126566368-8b79a895-0e0a-40ed-ab4f-26e500487c98.png)

Introducing this setting can open the door for merchants to create sections with readability issues, but we believe that giving them more flexibility to express their brand if important. We should show a color background by default to help educate merchants on the importance of having text be readable: Text over images is considered bad for accessibility because it’s often hard to read the text. So we don’t want to be encouraging its use - by default. I’m okay with adding the checkbox, as long as the background is set by default for this section.

**Comment by PaulNewton** [comment]
@valeriegohier before this gets changed some screenshots that could help are of the **opposite** extreme:  large amounts of text through the three elements (heading text, subtext, and button text) especially if any are capable of line breaks.

This will help make clear if removing whitespace alone is the best approach as it's pretty common to end up with banners with squished text in banners because the design only accounted for a couple of words when merchants **aren't** going for concision in their messaging.

**Comment by Oliviammarcello** [comment]
Improvements:

- [ ] Instead of the box having a fixed width, let's change it to adapt to the content added. The max-width should be changed to 510px on desktop.
- [ ] The minimum width should be 50px on either side of the content added (on desktop.)
- [ ] I believe that screenshot is out of date when it comes to the spacing between the heading and text, but it should follow what is done in the screenshot below. 
<img width="603" alt="Screenshot 2021-07-21 at 9 52 38 AM" src="https://user-images.githubusercontent.com/60230008/126531900-43deb2d7-04c2-47d1-9bb5-1e745ca832ce.png">

The box width on mobile does not change since it never covers the images.

**Comment by Oliviammarcello** [comment]
Additional improvements:

We are adding an option to remove the box and add an opacity to the images on desktop. 
- [ ] Add "Desktop layout" setting and "Desktop overlay opacity"
- [ ] Add "Heading size" setting to allow merchants to choose between H1 and H0

Settings and screens can be viewed on [Figma here.](https://www.figma.com/file/JcYdswrk2JhqBTGBVWPM7J/Dawn-2.0?node-id=11173%3A86579) The copy is currently a WIP. This line of text will be removed when it has been updated.

**Comment by PaulNewton** [comment]
>@Oliviammarcello Add "Show text box on desktop" setting and "Image overlay opacity"

For design notes about image integrity in dawn ,
 While ecom hero banners have evolved to innately have images covered with all types of stuff what's the driver for obscuring further with opacity? 
Solely addressing contrast issues? or is an opacity overlay just not considered as ["content" for the purposes of what counts as affecting image integrity](https://ux.shopify.com/next-generation-theme-design-5aae94f6d44c#:~:text=overlays%20content%20on%20them)..

>Add a setting to allow merchants to pick if they want text on top of or below their image on mobile

This seems to bring the integrity back up solely for mobile, is the intent that if a merchant wants this for desktop they would just add a text block under the banner for the same effect?
