### ISSUE TITLE
Account page: Orders pagination is not correct.

### ISSUE THREAD

**Issue by Shine-Developer** [Shopify/dawn#2202]
Current behavior: Suppose the storefront user has placed around 150 orders; it shows the pagination up to 5 only on the account display, which takes 20 orders per page, so the maximum number of orders that users can see is 100 here. 

Expected behavior: On the account page, all placed orders should show without limitations.

Version information (Dawn, browsers, and operating systems)

- Dawn Version: 7.0.1
- Chrome Version: 108.0.5359.125
- Windows Version 10 pro

Additional context/screenshots
![image](https://user-images.githubusercontent.com/75617426/211486226-04f7e52e-b83d-400f-a7f1-2ecce5775b2f.png)

**Comment by ludoboludo** [comment]
Hey @Shine-Developer in this example, did you have lots of test orders done ? 
Seems like the culprit comes from the fact that the pagination doesn't take into account test orders. 
Ill close this issue and keep https://github.com/Shopify/dawn/issues/2230 open if it's that ok with you 👍 

But curious to hear back and confirm that you have test orders in that account.

**Comment by Shine-Developer** [comment]
Hey @ludoboludo, Yes, I did test orders here. And it's okay that you have closed this. I'll check the other one, #2230 for more updates.
