### ISSUE TITLE
Sign up form: Error message Copy Update

### ISSUE THREAD

**Issue by nicklepine** [Shopify/dawn#23]
### Here's what the text should be:

Title:
`Double-check your email and password`

Subtitle:
`The information entered was incorrect. To login, re-enter your email and password.`

![image](https://user-images.githubusercontent.com/15196462/122942833-7d65ea00-d344-11eb-97c8-e79b035d130c.png)

**Comment by tauthomas01** [comment]
From the screenshot

"Please adjust the following:" is a global message not only applied on signup form, but on other pages such as article, login, register so I'm not sure if changing the text to "Double-check your email and password" would be relevant because the error message field doesn't always contain email errors.

The "Incorrect  email or password" error message is generated on the backend, so it's not possible to edit.

**Comment by propero-in** [comment]
@tauthomas01 , maybe you are right, in that case we can pull a different message for login form error

**Comment by melissaperreault** [comment]
Closing because Thomas's answer is true. We can revisit another time if we have the ability to curate better those messages.
