### ISSUE TITLE
Change language around "Showing X of Y products" 

### ISSUE THREAD

**Issue by nicklepine** [Shopify/dawn#238]
**Describe the current behavior**
When no filtering options have been applied we display "Showing X of Y products". 

Could we instead display "Showing Y products" given no drill down on product results has happened yet. 

Only when a filter has been applied could we display "Showing X of Y products" to emphasize that you are seeing less products that originally. 

**Describe the expected behavior**

**Version information (Dawn, browsers and operating systems)**
- Dawn Version: 1.1.0
- Chrome Version 91.0.4472.114
- macOS Version 11.3.1

![image](https://user-images.githubusercontent.com/8127145/126508471-aa9eece4-c7cf-4f92-a69b-685748e198c5.png)

**Comment by PaulNewton** [comment]
Collection product count text, CPCT(counters), uses [collection.products_count](https://shopify.dev/api/liquid/objects/collection#collection-products_count) & [collection.all_products_count](https://shopify.dev/api/liquid/objects/collection#collection-all_products_count) in **duplicated*** localized 1 liners with translation  keys from a [locales file vs being from the sections locales schema](https://shopify.dev/api/liquid/filters/additional-filters#section-locales-vs-theme-locales).
*_see breakdown for duplication issue_

Unless there's a way to short-circuit this with the [default filter](https://shopify.dev/api/liquid/filters/additional-filters#default) , it does not look like any new liquid features were added to specifically facilitate **translations** based on storefront-filtering either as filter ,or `t:` locale parameters, that would keep CPCT to a singlet output using only [interpolation](https://shopify.dev/themes/architecture/locales/storefront-locale-files#interpolation) and [pluralization](https://shopify.dev/themes/architecture/locales/storefront-locale-files#pluralize-translations).

 So a first run though looks like the change will either have to have conditional logic , or be split into two string outputs while  also expanding the available localizations at the same time, or making localization keys for filtered&unfiltered text.

### Psuedocode 
`{% if filters.values.size == 0 %}Showing Y products output text {% else %}{{ 'sections.collection_template.product_count' | t: product_count: collection.products_count, count: collection.all_products_count }}{% endif %}`

Split outputs alternative
`  {{ 'sections.collection_template.product_count' | t: product_count: collection.products_count }}{{ 'sections.collection_template.product_count_all' | t: count: collection.all_products_count }}`
in tandem with:
```
      "all_products_count": {
        "one": "",
        "other": " of {{ count }}"
      },
      "product_count": {
        "one": "Showing {{ product_count }} product",
        "other": "Showing {{ product_count }} products"
      },
```
Nit - This structure can result in the sentence: "Showing X products of Y", so `all_products_count` would probably be better with the text `total` for "Showing X products of Y total". 
And this method slightly increases the chance of maintenance mistakes as both outputs {{}}{{}} and localization pluralizations,  have to be maintained in sync.

Parity - Notice that `all_products_count` is used instead of `product_count_all` to keep parity with the actual collection attribute [all_products_count](https://shopify.dev/api/liquid/objects/collection#collection-all_products_count.) , this also indicates that the locale key `product_count` should probably be changed to `products_count` in this fix as well to reflect `[collections.products_count](https://shopify.dev/api/liquid/objects/collection#collection-products_count) or that naming conventions that supercede simplying api usage should be documented in the dawn repo.


### CPCT Structure Breakdown
The locale key is `product_count` https://github.com/Shopify/dawn/blob/fe161810935b62ab84eac131a026a5703ad6de1e/locales/en.default.json#L238-L241

Also when there is only 1 product in a collection this results in the clinical _Showing 1 of 1 product_  instead of specifically stating there is only 1 product in this collection in a more human way i.e _Showing 1 product_. _Showing the only product_ ,_There is only 1 product here_, etc , or not displaying this text at all. 

The text generation of CPCT also suffers from code duplication of this line:
`{{ 'sections.collection_template.product_count' | t: product_count: collection.products_count, count: collection.all_products_count }}`
This should be  refactored so that in this section, or future derivatives, any change like this does not constantly require edits in **3 different locations** ,
1. https://github.com/Shopify/dawn/blob/1cda1dcbf932db09e1d17151d15bd38c8e4b4b7f/sections/main-collection-product-grid.liquid#L240
2. https://github.com/Shopify/dawn/blob/1cda1dcbf932db09e1d17151d15bd38c8e4b4b7f/sections/main-collection-product-grid.liquid#L446 
3. https://github.com/Shopify/dawn/blob/1cda1dcbf932db09e1d17151d15bd38c8e4b4b7f/sections/main-collection-product-grid.liquid#L467

A general solution here will help with other text duplications that may exist in the theme.

Note: _CPCT sometimes need to also account for any special pagination behaviors but it doesn't look like this is an issue for dawn currently as pagination hints are contained at the bottom of collections in the [pagination snippet](https://github.com/Shopify/dawn/blob/main/snippets/pagination.liquid)_.

New related concepts:
https://shopify.dev/themes/navigation-search/filtering
https://shopify.dev/api/liquid/objects/filter
https://shopify.dev/api/liquid/objects/filter-value

Other counters:
 search results, cart item counts, articles, and pagination loosely related

**Comment by tyleralsbury** [comment]
To Paul's point, I do think that currently the easiest thing to do would be to use conditional logic based on whether there are any filters applied.  There is some complexity around proper pluralization as well.  Personally, I would consider just leaving it with the "Showing X of Y" in all cases to reduce the amount of logic needed since it doesn't really break the experience at all.

There is an interesting case to be made for the more natural tone of "showing the only product" when there's only one, etc... which could be something that we could actually create a catch-all Liquid filter to handle.  Something like a `{{ collection.product_count_text }}` that could figure out things like...

1. How many products are there?
2. Out of how many?
3. What's the pluralization situation for all of this? (Locale specific)
4. Is there only one product?  What's the most human readable way of saying that?
5. Is there some huuuuge number of products?  Should it say "Showing X of 1000+ products"  in that case?

Some very interesting things to think about @PaulNewton .

cc @Thibaut is this something you're aware of us having thought about for the platform to expose?
