### ISSUE TITLE
[Country/Region and Language selector] Support gradients ?

### ISSUE THREAD

**Issue by ludoboludo** [Shopify/dawn#2384]
## Describe the current behavior
Locales selectors do not support gradient background.

## Describe the expected behavior
Should locales selectors support them ?

## Version information (Dawn, browsers and operating systems)

- Dawn Version: 8
- Chrome Version 108.0.5359.124
- macOS Version 13.1

## Possible solution
Tweak the colors for the localization form as well as the `disclosure__list-wrapper`. 

## Additional context/screenshots

<details>
<summary>Screenshot</summary>

![](https://screenshot.click/13-15-2ryed-r5a3x.png)
</details>

cc: @melissaperreault

**Comment by melissaperreault** [comment]
## UX details

> Show we support gradients in the **header** locales selectors? 

The short answer is, yes! (Includes drawer - to be tested)

> Show we support gradients in the **foofer** locales selectors? 

Short answer is, no. 


**Rationale**
Since the gradient would remain, in general, predictable for the header because the height is more _controlled_, I don't believe we need the fallback solid color applied here. Supporting the gradient smoothly will help polish the details of an already cluttered listing. Of course this will rely solely on merchants extra care and attention to hand pick a good high contrast foreground color to stand out well. It's already the case to set their menu items, icons, and now selector labels for success to remain legible.

**Comment by ludoboludo** [comment]
PR created to fix it 👍
