### ISSUE TITLE
Mobile Header - Remove Account Icon

### ISSUE THREAD

**Issue by nicklepine** [Shopify/dawn#246]
**Describe the current behavior**
The account icon surfaces on the mobile header, even though we added a Log In CTA in the menu drawer. 

Video explanation: https://screenshot.click/21-41-g75ej-414de.mp4

**Describe the expected behavior**

- [ ] Account icon is removed from the mobile header
- [ ] Logo is always centered on the mobile menu. 

**Version information (Dawn, browsers and operating systems)**
- Dawn Version: 1.1.0

**Comment by PaulNewton** [comment]
Design wise this is the result of the mobile menu being below the mobile header unlike some designs that visually hide the entire header menu , such as by overlaying the entire mobile menu over all other theme interfaces.

@nicklepine  This is needed for customer centric stores that expect a login , _and customer account page link_, to **always** be visible without digging into UI's or menus.
Duplication isn't desirable but is the design issue still relevant when the setting sticky header is turned off and the mobile header is scrolled **offscreen**  after it's been opened? (see _Dupes scrolled offscreen_ image below)

Recommend logic based on [customer account settings](https://help.shopify.com/en/manual/checkout-settings/customer-accounts) 
- If customer accounts are required both icons should show
- If customers accounts are options show both based on setting
- If customer accounts are disabled continue to use current behavior of not showing the login
  -  _login icons for things like wholesale account inquiries should be left to advanced customizations_

Submitters will also want to check :
- the mobile menu layout to be sure large menu's aren't able push this login offscreen making the login buried twice over if this change happens. 
-  A setting or a situation where the the mobile menu fully obscures the mobile header so that duplicate icons aren't seen anyways


💣 If there is, or will be,  an obscuring situation this issue **INVERTS** and the other icons(_cart,search_) would instead need to be duplicated **into** the mobile menu as well instead of removing the login.

Dupes scrolled offscreen
![image](https://user-images.githubusercontent.com/47228209/126602510-0259d0c7-cb23-487e-be04-7130945e73f9.png)

Dupes highlighted
![image](https://user-images.githubusercontent.com/47228209/126599772-10c27567-17a6-4403-9d00-26557df6321c.png)

**Comment by tyleralsbury** [comment]
Tagged as low effort for the issue as described, though it would be good to get some design eyes on the comment made by @PaulNewton since there's a lot of thought put into this.

cc @melissaperreault @Oliviammarcello @wiktoriaswiecicka @jendunnam

**Comment by melissaperreault** [comment]
I'll need to catch up on the whole experience with the team but the original intention was to never display the login icon in the mobile header unless there was no menu attributed to the store when Account was activated on the store. Otherwise Account icon login was only available in the drawer as per initial UX.

This was the intention when no menu:

![](https://screenshot.click/21-08-l1z7o-cm7sx.png)

cc. @Guillaumegranger1
