### ISSUE TITLE
Announcement bar: Tweak slideshow animation

### ISSUE THREAD

**Issue by stufreen** [Shopify/dawn#2550]
### Summary

Update slide animation in the announcement bar to be vertical or fade-in fade-out, instead of sliding right-to-left.

### Designs

https://www.figma.com/proto/ZywFj2r8xci8rMHriRYfUX/Banner-Animation-Tests?page-id=0%3A1&node-id=1-542&scaling=min-zoom&starting-point-node-id=1%3A542&show-proto-sidebar=1

Confirm with UX which option to use (leaning towards options 2 or 3)

### Details

In https://github.com/Shopify/themes/issues/398 we updated the announcement bar to be a slideshow, instead of stacking announcements.

However the animation is a little too prominent and we want to make it more subtle.

This issue is to update the animation in one of two ways (to be determined):
1. Cross-fade between slides (fade in/fade-out)
2. Slide in from bottom to top with a fade-in fade-out of opacity

**Comment by bredowmax** [comment]
@stufreen this may actually solve a problem I've noticed in the latest version of Dawn: If merchant set up several announcement bars then shopper can scroll the website horizontally. See video

This is hardly noticeable on en emulated device but becomes more apparent if you're holding a phone in your hands. If my scroll-up/scroll-down gestures are not very precise, the entire website moves to the side.

Hiding announcement bars so that only one is visible fixes this.

https://user-images.githubusercontent.com/30573532/236909453-a689aef7-41f7-4bcd-a282-ab1e762b3969.MP4

**Comment by eugenekasimov** [comment]
> @stufreen this may actually solve a problem I've noticed in the latest version of Dawn: If merchant set up several announcement bars then shopper can scroll the website horizontally. See video
> 
> This is hardly noticeable on en emulated device but becomes more apparent if you're holding a phone in your hands. If my scroll-up/scroll-down gestures are not very precise, the entire website moves to the side.
> 
> Hiding announcement bars so that only one is visible fixes this.
> 
>  RPReplay_Final1683572241.MP4

Hey @bredowmax thanks for brining this up. We will investigate this 👍

**Comment by melissaperreault** [comment]
> but it becomes more apparent if you're holding a phone in your hands

@bredowmax I am unable to replicate both on my Android and iPhone, on our demo store linked on main branch. Can you share the steps to replicate please?
