### ISSUE TITLE
[Cards and Buttons] Raise effect on hover

### ISSUE THREAD

**Issue by kjellr** [Shopify/dawn#2574]
## Describe the enhancement you'd like

Add a "raise" effect on hover for card and button elements. 

Example: 

https://user-images.githubusercontent.com/1202812/234607782-3a5673cd-b459-49cb-bdc1-b30ca433ffe2.mp4

## Additional context/screenshots
 
- Inspired by the explorations in #2229.
- The settings for this feature will be part of the new "Animations" section in Theme Settings, also utilized by https://github.com/Shopify/dawn/pull/2367 and #2452.

**Comment by bredowmax** [comment]
Just played around with the newest Dawn version and noticed that the shadow of a card covers cards before (left, above) but is covered by cards that come after (right, below) in the same stack.

Since the effect is a 'lift' effect, I argue the shadow should cover ALL cards.

Experienced:
<img width="447" alt="Screenshot 2023-04-27 at 1 48 45 PM" src="https://user-images.githubusercontent.com/30573532/234958796-bb152f47-370c-4b41-bf07-2558e9de0bfe.png">


Expected: (this is a mockup where I manually tweaked the z-index)
<img width="432" alt="Screenshot 2023-04-27 at 1 53 06 PM" src="https://user-images.githubusercontent.com/30573532/234958578-fd44d9f2-ed91-4d5a-bfc1-1cf04005722a.png">
