### ISSUE TITLE
Layout shift in announcement bar, in mobile view

### ISSUE THREAD

**Issue by metamoni** [Shopify/dawn#2632]
## Describe the current behavior
In mobile view, when opening the Menu drawer and navigating to a different page, there's a slight layout shift happening in the announcement bar.

## Describe the expected behavior
The spacing in the announcement bar should not change when navigating between different pages

## Version information (Dawn, browsers and operating systems)

- Dawn Version: 9.0.0
- Chrome Version 113.0.5672.92
- macOS Version 13.3.1

## Additional context/screenshots
[Video](https://videobin.shopify.io/v/lwO00k)
[Slow motion video](https://videobin.shopify.io/v/MMnEMd)

## Steps to replicate
- [ ] go to the theme editor or the online store, in mobile view
- [ ] open the menu and navigate to a different page
- [ ] notice that the content in the announcement bar shifts and seems to "snap into place" after the page loads

**Comment by naxorn** [comment]
I'm able to reproduce this still on ```main``` as of may 24th...

# Steps to replicate - Option 1 - delete elements
1) Create 3 announcement bars in the theme editor
2) Open the website outside of the theme editor -- didn't try to reproduce in theme editor
3) Delete all block elements below the header section or delete enough elements below header until page content is shorter than page

You might get something like this:
![image](https://github.com/Shopify/dawn/assets/67534064/18916e49-be8b-4bc3-b43a-25a1def4e3a9)

# Steps to replicate - Option 2 - throttle network speed
1) Do steps (1) and (2) above
2) Open debugger console and do the following:
    * Disable cache
    * Throttle the network speed -- I found 60 kbit/s a good value to see the issue soon enough and have time to react
&nbsp;&nbsp;&nbsp;![image](https://github.com/Shopify/dawn/assets/67534064/89cbe665-633a-4c4e-8134-4c4f0d33b46d)
3) Open any page, such as the main page, or contact page which is nice and short
4) Wait for the slowed page to load.  When the third announcement bar appears it will occupy over 75% of the available space.  To inspect the page, I found just pausing the debugger was useful.

You should get something like this:
![image](https://github.com/Shopify/dawn/assets/67534064/284a705d-0bd2-48af-a068-1c829445a768)

# What's the cause?
When the page content is smaller than the screen height, such as in the early stages of loading, the third visible block element of the ```body``` will become full-height due to the following in theme.liquid:
```css
      body {
        display: grid;
        grid-template-rows: auto auto 1fr auto;
        grid-template-columns: 100%;
        min-height: 100%;
        /* ... more ... */
      }
```
When the page loads further, more elements are added to the page, so there is no extra space and ```grid-template-rows``` is ignored.

# Possible Solutions
Most pages will have content longer than the view port height, so ```grid-templates-rows``` will usually be ignored anyway.  Removing ```display: grid``` and grid options from the body css fixes this issue and hopefully doesn't introduce any :).  You could also use ```display: flex; flex-direction: column;```, but unless more flex features are needed, is not necessary.

# Issue is not limited to announcement bar
The body just needs at least 3 elements and a page content shorter than the viewport height.  The third element always fills any remaining height:

![image](https://github.com/Shopify/dawn/assets/67534064/2771efa0-6280-4773-9035-1cbefd184a7b)

# Browser Details
* Chrome 114.0.5735.91
* Windows 10

**Comment by naxorn** [comment]
@metamoni Would you please re-open this issue?  I've outlined replication steps above.

**Comment by naxorn** [comment]
That solution won't fix all scenarios though, such as people not using the drawer.  I gave up waiting for a fix for this and rolled my own.  I'm sure there's a better way, but I settled on just removing the grid and letting the browser do it's thing, so elements determine their own heights:

theme.liquid Before:
```css
body {
  display: grid;
  grid-template-rows: auto auto 1fr auto;
  grid-template-columns: 100%;

  /* ... more stuff ... */
}
```

theme.liquid After:
```css
body {
  display: flex;
  flex-direction: column;

  /* ... more stuff ... */
}
```
