### ISSUE TITLE
Footer has extra empty space

### ISSUE THREAD

**Issue by rozinashopify** [Shopify/dawn#2691]
## Describe the current behavior
When unchecking the "Show email signup" setting in the footer the space and lines around it stays in the footer. 

## Describe the expected behavior
This extra space and lines should not be there when the email sign up is turned off. 

## Version information (Dawn, browsers and operating systems)

- Dawn Version: 9.0.0
- Chrome Version 114.0.5735.90 
- macOS Version 13.4

## Additional context/screenshots
https://screenshot.click/31-18-8cc0e-9qmzb.png

**Comment by qui-gon-jon** [comment]
Hi @rozinashopify 

It looks like the space is only appearing because both the "Enable Follow on Shop" and "Show social media icons" settings are checked, but neither are configured. The space is reserved for social media icons and the follow on shop button. If you disable both of those settings as well, then the extra space is removed: [Screen recording](https://screenshot.click/07-57-hil46-9ctjm.mp4)
