### ISSUE TITLE
Progressive enhancement: Sort by dropdown

### ISSUE THREAD

**Issue by nicklepine** [Shopify/dawn#284]
**Describe the enhancement you'd like**

Explore introducing a Dawn-styled dropdown for Sort by, thereby replacing the browser-provider one. 

Given Filtering and Sort are so close to one another, it can feel odd for buyers to apply filters from styled dropdowns, yet applying a sorting option from the browser dropdown. The experience doesn't feel cohesive. 

![image](https://user-images.githubusercontent.com/8127145/127326398-bf408378-5c47-421d-8f4e-50a7e43cc9ba.png)

With this exploration, let's try to understand if: 
1. we can achieve something that is accessible, and we feel good about
2. that doesn't introduce too much extra code / JS. 
3. Look into applying this to Sort dropdown, as well as the Variant picker dropdown on product pages

**Comment by PaulNewton** [comment]
>Look into applying this to Sort dropdown, as well as the Variant picker dropdown on product pages

Considering doing this for `<select>`'s **after** exploring this specifically for variants first.  Because Filters and Sort get duplicated in the mobile menu so the testing and tech debt is basically doubled, meanwhile variants-pickers are such a first class feature that issues are more likely to surface in critical feedback earlier when trying to transcend the native `<select>` paradigm. 
 And any change on `<select>` UI's on product pages has more impact on merchants design choices than just sort on collection pages as currently it's two options with no in between for variant display type: buttons or lists.
Then taking the lessons learned on variants to apply the production change to the Sort menus first to get live testing&feedback before applying it to variants in production.

The catch with `<select>`'s is that with cross browser compatibility the OS level dropdown does a **ton** of legwork and provides ALOT of benefits, particularly on mobile devices that provide things like a partial or near full screen picker UI for the options. A big pain point in themes is ensuring **resilient tap target sizes** against downstream design choices like seemingly sane changes like smaller fonts or whitespace shrink|creep by merchants creating an invisible user frustration. Native mobile UI pickers play defense for us intrinsically.
A biggie for **desktop** is selects allow character typeahead to select options and any change should have that as a first class goal.
 
| Example - iphone6s v13.7 option Picker |
| --- |
| ![image](https://user-images.githubusercontent.com/47228209/127804924-92c04a84-e0bb-455c-b24c-df90c89606d6.png) |

The Select does have a different border style behavior than the Filters, and without a design reference it's not clear to external contributors which is correct.
( _there are several border styles issues, such as #203 but most are not all are cross referenced_ )
| Filters  | Sort |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/47228209/127805371-f4c98c39-42b8-4798-bd1e-780c55ca3989.png)  | ![image](https://user-images.githubusercontent.com/47228209/127805813-8be87830-b5a1-4cdf-bd6e-8e88daa79c0d.png)  |

Another  UX upside|downside of this change could be that the Sort options could become **text searchable** in the page like the Filter top level options, though the inner drilldown options are not searchable). I've never encountered a use case for that on stuff like sort menus though, 🤔 BUT this could be super useful on product pages to be able to higlight options through search.
![image](https://user-images.githubusercontent.com/47228209/127803884-04c0eb50-c073-4bcf-8752-5d38b1ffa88e.png)

, currently text in Sort options are not consider in a browsers page find(ctrl+f|ctrl+g) highlighting, at least in chrome-latest.
in the image below trying to find the text "Availability" through the page-find gets no results.
![image](https://user-images.githubusercontent.com/47228209/127804200-db39df54-4350-4462-8831-db7146af56c3.png)

Other considerations:
If using the hidden `<select>` technique to control this UI layer; keep in mind the variety of customizations merchants make to the theme dropdowns, such adding iconography to the options (i.e. ↓ in: _Alphabetically , A-Z ↓_) _that my not be in the locale translation_ , or the rare adding a default option "Choose an option" to be the first option. So indirect UI's should probably exactly copy the `innerText `of the `<select>` 's `<options>` elements ;  _and 🤔 possibly propagate any&all attributes such as data-attributes in addition to `value` , along with being sure to to fire a change event for third parties such as apps to subscribe too._

Custom UI's for a list of choices replacing a `<select>` should strive to allow character typeahead to focus|highlight options.

**Comment by PaulNewton** [comment]
For mobile view should the options be in a revealed panel like filters
| Example - mockup of mobile sort behaving as a filter |
| --- |
| ![image](https://user-images.githubusercontent.com/47228209/127820458-86f0070f-8e90-403a-b91d-d6fecb072f51.png) |

**Comment by tyleralsbury** [comment]
In addition to what Paul has already mentioned, there are some interesting technical challenges here.

The filtering uses a form to handle UI updates.  This means that by changing it from a native `<select>` to something else, we are actively going against the web native approach of using the basic browser feature for its intended purpose.  We will need to use JS to update a hidden input in its place or maybe use Radios instead.

If we do go the JS route, we will need to have two separate components - the existing dropdown for `no-js` and the new UI for JS enabled browsers, which means more complexity on the Liquid side.

This is the case for filters but also for any other elements that we may want to do this with i.e. the variant dropdown, etc... since they are all relying on the native `<select>` element because they are all using forms.

We need to be really careful about not bloating all of the elements of our code - Liquid, CSS, and JS are all going to be larger as a result of this change.  We may also be running headfirst into some accessibility concerns that the native `<select>` element resolves out of the box around keyboard navigation, etc...

**Comment by KaichenWang** [comment]
Additional notes: https://github.com/Shopify/dawn/issues/198#issuecomment-891099340
