### ISSUE TITLE
Improve photo quality

### ISSUE THREAD

**Issue by Miktau** [Shopify/dawn#289]
**Describe the enhancement you'd like**
A clear and concise description of what you want added to Dawn. Add any considered drawbacks.

**Describe alternatives you've considered**

**Additional context/screenshots**
Maybe a screenshot or design?

**Comment by Miktau** [comment]
Product photos have poor quality. 

added one of our product photos and one from nelly. The nelly photos are more zoomed in and have much better quality. 

> _
![Screen Shot 2021-07-29 at 13 46 17](https://user-images.githubusercontent.com/61705825/127487476-b0668b7f-abba-4cfa-bad7-0b607bc09a2f.png)
![Screen Shot 2021-07-29 at 13 45 28](https://user-images.githubusercontent.com/61705825/127487484-7df459d5-4992-457d-8838-52b8a7737a67.png)
_

It was not a problem with the turbo theme

**Comment by tyleralsbury** [comment]
Taking a look at this.  I believe it has to do with the fact that we've expanded the width of the page to about 33% bigger, but didn't change the sizes of the images being rendered to the page. Thanks for creating the issue!

**Comment by Miktau** [comment]
It is good on mobile but its still not good on desktop. Can you look into it?

**Comment by Miktau** [comment]
I see the issue lays in small files, but it has not been a problem before when we uses theme from out of the sandbox

**Comment by tyleralsbury** [comment]
There's currently an open PR that is looking to broaden our handling of image quality issues:

https://github.com/Shopify/dawn/pull/668

Can you give some specific examples of where you're running into problems? Useful details would be:

* Screen resolution
* Original image dimensions
* Viewport size
* Section where the issue is happening
* Settings of that section
* Page width setting
