### ISSUE TITLE
Volume Pricing: variants that dont have vol pricing will have a big spacing gap

### ISSUE THREAD

**Issue by sofiamatulis** [Shopify/dawn#2932]
Original comment: https://github.com/Shopify/dawn/pull/2889#discussion_r1270868669

**Option 1: Show greyed out table**
- All of the elements will be in the same position and no layout shift
- If blocks are re-ordered it wont affect it
- More real estate being used but no real information is there
- 
**Option 2: Remove the extra spacing**
- Layout shift will occur when you change variants
- Especially if blocks are re-ordered, the layout shift can be more jarring
- Real estate being used with information that is not useful (greyed out blocks). At the same time, unavailable variants would not offer any information to begin with

**Decision:** Option 2

_Extra context:_

Option 2 is more future proof in the sense that if we do add new information in the future, its easier to just not show it instead of having to think what to do with the new spacing for the new information.

We already have some small layout shift because there may be a table that the show more exists or the unit price exists or not.  But some layout shift already exists:
https://screenshot.click/02-44-v1jzm-qoxnm.mp4

**Comment by edmund-teh** [comment]
@sofiamatulis Maybe we can discuss addressing some of these things from my video here: 
https://screenshot.click/01-20-bivod-ahada.mp4

- [ ] Adding a string that says Variant unavailable where the price used to be, while still leaving room below where Volume pricing available used to be— to avoid layout shift.

- [ ] Removing the spacing gape where quantity rules and volume pricing used to be— layout shift can occur here because we only need to avoid it where buyers are selecting Variant pills or dropdowns.

Figma prototype [here](https://www.figma.com/proto/AxH2jkpnLbZXPR8NbgaoaK/Volume-pricing-in-flagship-themes?page-id=1257%3A309&type=design&node-id=1257-594&viewport=193%2C195%2C0.21&t=LF27oG1fLDEmP0oz-1&scaling=scale-down-width&starting-point-node-id=1257%3A594&show-proto-sidebar=1&mode=design)
Figma file [here](https://www.figma.com/file/AxH2jkpnLbZXPR8NbgaoaK/Volume-pricing-in-flagship-themes?type=design&node-id=1257-309&mode=design)

https://screenshot.click/Current-Dawn-main.png
https://screenshot.click/Sofias-fix.png (#2889)
https://screenshot.click/Proposed-change.png
