### ISSUE TITLE
404: Menu Navigation is empty

### ISSUE THREAD

**Issue by nicklepine** [Shopify/dawn#55]
**Issue**
When navigating to 404 - the menu navigation doesnt display any menu links

**Steps to reproduce:**
1. Go to 404
2. Open menu, observe no links

Video: https://screenshot.click/24-27-6jv53-rlsn8.mp4

**Comment by tauthomas01** [comment]
This is an odd bug. I can see the menu in the editor, but it seems like the Liquid drop isn't exposed.

`{{ section.settings.menu }}` returns `main-menu` handle on 404 page, but `{{ section.settings.menu.links }}` does not return a link list drop.

Maybe it's related on how the 404 page is handled on the backend.

cc. @Thibaut 

[![alt](https://screenshot.click/29-52-ua8qu-tpwpr.png)](https://screenshot.click/29-52-ua8qu-tpwpr.png)

**Comment by maximevaillancourt** [comment]
We're currently trying to render all 404s from Storefront Renderer, I'll update this once we're there.

**Comment by maximevaillancourt** [comment]
This should now be resolved. 👀 

Storefront Renderer now renders all storefront read traffic. ✅ 

cc @emmack

**Comment by maximevaillancourt** [comment]
Follow-up: we just disabled this behavior to prevent an unrelated problem, so menus will be empty again until Monday.

We'll resolve this next week.

**Comment by bbbpppolly** [comment]
Is this really fix now? I tried to use Dawn and it looks like the menu still goes away. Even in the editor.

**Comment by maximevaillancourt** [comment]
Thanks for the report, @bbbpppolly. Looking into it.

**Comment by maximevaillancourt** [comment]
The menu navigation is now visible for 404s in the editor. ✅ 

We're looking into potential solutions to fix this bug for unexpected 404s in non-editor scenarios. 👀

**Comment by cbepxpa3ym** [comment]
The issue still exists. Layout is broken, menus do not exist (header and footer).
https://dawn-theme-default.myshopify.com/non-existing-page

Please, fix ASAP.

**Comment by ninetales** [comment]
This has still not been fixed.

**I tested this in the preview with the latest Dawn theme**

404 page not working.
The menu disapears and the css stops working to a certain degree. 

The problem even arrises when you do  the following:

1. Visit addresses (myshopify.com/account/addresses).
2. Click on "add a new adress".
3. Click on "add adress" **without** filling in the form.
(The same problem if you partialy fill in the form and click "add address"). No error messages about missing inputs.

In this case you don't get a 404 page, instead the menu disapears and the css breaks. Try to refresh the page and it just want to send the form once again without any success.

**Comment by maximevaillancourt** [comment]
Thanks for the reports. We are aware of this problem and are working on a fix.

**Comment by ryanaldred11** [comment]
Hey team, I found that menus are not being rendered on the account activation page as well. 

It seems likely that it's caused by the same underlying reason, so I've added the context to this issue but I could create a new one if you prefer.


### Example

[![alt](https://screenshot.click/25-24-qzks6-57hyr.jpg)](https://screenshot.click/25-24-qzks6-57hyr.jpg)

[![alt](https://screenshot.click/25-24-k7mln-hdro7.jpg)](https://screenshot.click/25-24-k7mln-hdro7.jpg)

[![alt](https://screenshot.click/25-23-rute5-hmqrb.jpg)](https://screenshot.click/25-23-rute5-hmqrb.jpg)

[![alt](https://screenshot.click/25-24-u0nja-8fpgb.jpg)](https://screenshot.click/25-24-u0nja-8fpgb.jpg)

### Steps to replicate

1. Create an account in the customer section of your admin
2. Click `send account invite`
3. Go to your inbox, open the email and click the link to activate your account
