### ISSUE TITLE
Image Banner: Height Setting

### ISSUE THREAD

**Issue by nicklepine** [Shopify/dawn#552]
The Image Banner section doesn't offer much flexibility in terms of section height. Even when adding a short image, we're preserving a min height thats quite tall.  Some merchants may want to use this section, not as their hero section, or want a shorter hero image banner, so exploring adding more flexibility in terms of section height can be beneficial. 

Video Explanation: https://screenshot.click/21-06-0h9wd-9al1g.mp4

**Comment by melissaperreault** [comment]
## UX Update

After some investigation here is the most successful update without introducing a breaking change and offering the flexibility merchants need. (Screenshot)

- [ ] Add a new `select` setting named `Image banner height` to manage the height and offer 3 sizes
   - [ ] Small: 42rem
   - [ ] Medium: 56rem (Default)
   - [ ] Large: 72rem
- [ ] We can't remove the `Adapt section height to first image size`, so we'll use it to overwrite the `Image banner height` setting and offer the flexibility of "Adapt to image" like we do on other sections. Image banner is particular because it can have up to 2 images, so we'll need to keep it as it is.
   - [ ] We'll need to add an info text to inform merchants of the impact when this setting is set to `true`.
- [ ] We'll need to add padding values for the select options of the `Desktop text position` setting to always have the box displayed where selected.
   - [ ] Top: `padding-top: 15rem;`
   - [ ] Center: Keep as it is
   - [ ] Bottom: `padding-top: 15rem;`

cc. @gretchen-willenberg We are doing an update on the Image banner section and would love your input for the right setting content for merchants. Let's sync!
