### ISSUE TITLE
Email Form Validation Bugs

### ISSUE THREAD

**Issue by nicklepine** [Shopify/dawn#57]
**Issue 1:**
The Newsletter signup form doesn't validate email addresses properly. You can submit the form with an invalid format. 

1. Type an invalid email address in the newsletter signup field (i.e. 123@123)
2. Submit the form

video: https://screenshot.click/18-26-dymd2-mpxho.gif

From Tyler:

> It should be using input type="email" and its parent form should not have the novalidate attribute. This way, even with JS disabled, validation will happen.
> 
> See https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/email

**Issue 2:**

When I submit the email form without adding an email, I am brought to the challenge page. I would have expected the behavior to prevent me from submitting the field unless I had put something in it.

https://screenshot.click/21-36-1dh77-x9i70.mp4

**Comment by chrisberthe** [comment]
This has already been addressed. This was fixed by adding the `required` attribute to the relevant input, i.e. in the [footer section](https://github.com/Shopify/dawn/blob/main/sections/footer.liquid#L109) and [newsletter section](https://github.com/Shopify/dawn/blob/main/sections/newsletter.liquid#L36).
