### ISSUE TITLE
Add typography base sizes

### ISSUE THREAD

**Issue by melissaperreault** [Shopify/dawn#634]
## Describe the enhancement you'd like

We want to introduce typography base size. Merchants want to be able to change the base size of their theme to accomplish an aesthetic preference in multiple areas of the theme and this new setting will meet their needs.

Some merchants quotes:

> "_Menu: I would just like the text a bit bigger, I'm not sure of the exact size_"

> _"General: It would simply make it easier to adjust the font size for older customers"_

> _"Product cards: I would like a bigger size font for the description of my products, just a size up to the price will be great"_

Because we want to maintain a great balance, the options we'll offer wouldn't be too extreme as we don't want to break the successful grid and alignment.

Below are my initial suggestions but would like to pair with our dev to optimize the outcome and ensure no other dependencies are broken. ([Reference](https://screenshot.click/21-09-3hbb2-ljo51.png))

### Heading
I estimate the range should be from `26px` to `34px` and have an increment of `2px`.

### Body text
I estimate the range should be from `14px` to `17px` (Maybe 18px) and have an increment of `1px`.

### Visual reference methodology
I prefer with this issue to pair with a dev to see the changes IRL as oppose to try to mock up the changes in various screens as I want us to turn around quickly on the change.

**Comment by KaichenWang** [comment]
@melissaperreault 

Here are some alternative suggestions that would enable some level of customization while keeping settings simple and code changes to a minimal. Of course, this all depends on what merchant frustration we're trying to solve first and foremost; your suggestions above do provide more flexibility but would require more significant code changes. We can sync and go through the details together.

#### 1. Instead of a range (slider) setting, the setting could be a select (dropdown)

- This eliminates the use of `px` to describe sizes, instead using more abstract labels (small, regular, large, extra large). For headings, using `px` for a "base size" doesn't accurately describe what font size each type of heading (h1, h2, etc.) will be set to.

- We aren't limited to a range with fixed increments (26, 28, 30px, etc.). With the dropdown, we could potentially cover a broader range (with unequal increments)

![Screen Shot 2021-09-21 at 3 05 26 PM](https://user-images.githubusercontent.com/3710548/134232317-60b6b03e-27bc-4f43-b3c4-c9525cd2c999.png)
![Screen Shot 2021-09-21 at 3 05 20 PM](https://user-images.githubusercontent.com/3710548/134232351-dee3d7c4-348a-47df-97a7-5696d46cd48f.png)

#### 2. Instead of separate settings for Headings and Body, one single setting could be used to scale the UI up and down in size

- This ensures that the components we design always remain proportional (Headings, Body text, and the spacing between them)
- Icons and non-text UI elements also scale proportionally
- No need to separately adjust letter-spacing and line-height when font-size is increased/decreased
- Minimal code changes and testing

[See demo](https://os2-demo.myshopify.com/admin/themes/126418485270/editor?context=theme&category=gid%3A%2F%2Fshopify%2FOnlineStoreThemeSettingsCategory%2FTypography%3Ftheme_id%3D126418485270%26first_setting_id%3Dtype_header_font)

**Comment by melissaperreault** [comment]
Thank you @KaichenWang ! This is a great approach as well and I am glad that your suggestion brings both simplicity and strength to the system. I am adding some of your notes to our decision log for future references! 

- [ ] I would like to have an additional option in the list between `Large` and `Extra large` I find the step too big between the two visibly on the screens

What do you think of this?
| Label | Scale | example - body font-size | example - H1 font-size on desktop |
| --------------- | --------------- | --------------- | --------------- |
| Extra small  | 0.875x | 14px | 35px |
| Small | 1x | 16px | 40px |
| Medium | 1.25x | 20px | 50px |
| Large | 1.375x | 22px | 55px |
| Extra large | 1.5x | 24px | 60px |

- [ ] We'll need to add a title to distinguish this setting if it is a global one to `Font size `

**Comment by ethanclevenger91** [comment]
Depending on your font, the defaults are quite small. See https://porterhouseclothing.com/. The vendor label on a product card, for instance, is just absurd.

**Comment by KaichenWang** [comment]
@melissaperreault 

Created another [demo](https://os2-demo.myshopify.com/admin/themes/126427201558/editor?context=theme&category=gid%3A%2F%2Fshopify%2FOnlineStoreThemeSettingsCategory%2FTypography%3Ftheme_id%3D126427201558%26first_setting_id%3Dtype_header_font) with separate size setting for headings. This is for validating the approach; additional work needs to be completed to ensure all headings resize properly with the setting.

**Comment by melissaperreault** [comment]
## UX Update

After regrouping feedback internally, I am listing the important values that are driving our final approach/rationale:
- Have the ability to change the hierarchy between `Headings` and `Body` is important and key to express different tone and contrast.
- Scaling icons and non-text UI elements proportionally is key to maintain a strong system and cohesion
- Giving the perception of control to merchants is important through intuitive and effortless settings

### Separate the settings + range/slider
- The demos confirmed this is the experience we want to achieve, let's have both heading and body scale independently.
- I dont believe in offering smaller scale below 100% because we've set the most successful baseline sizes and when testing I could see unsuccessful outcome. This aligns with merchants wanting to increase the font size, not reducing it. ([See merchants quote](https://github.com/Shopify/dawn/issues/634#issue-998483892))
- Offering the `range` setting type is best to see quickly the result of your choice in the editor view as opposed to a `select` input type in this use case.


#### Setting details
[Visual reference](https://screenshot.click/21-09-eevev-ph0xk.png)

**_Heading_**

>    
    {
      "type": "range",
      "id": "font_size",
      "min": 100,
      "max": 150,
      "step": 5,
      "unit": "%",
      "label": "Font size scale",
      "default": 100
    }

**_Body_**

>    
    {
      "type": "range",
      "id": "font_size",
      "min": 100,
      "max": 130,
      "step": 5,
      "unit": "%",
      "label": "Font size scale",
      "default": 100
    }
