### ISSUE TITLE
Date is not rendering correctly on blog article pages

### ISSUE THREAD

**Issue by liamgriffin** [Shopify/dawn#90]
**Describe the current behavior**

On blog article pages, dates are not rendering correctly:
![image](https://screenshot.click/01-04-1iskj-lk0aa.png)

**Describe the expected behavior**

Should look like:

![](https://screenshot.click/01-17-4wkey-s3ftx.png)

**Device information (browsers and operating system)**
NA
**Possible solution**

Instances of `{{- article.published_at | time_tag: format: 'month_year' -}}` at 

https://github.com/Shopify/dawn/blob/c94813ac2eaef0db2b5dea62b353d70eea334c9a/snippets/article-card.liquid#L47
and 
https://github.com/Shopify/dawn/blob/c94813ac2eaef0db2b5dea62b353d70eea334c9a/sections/main-article.liquid#L33

should be changed to `{{- article.published_at | time_tag: format: 'date' -}}`

**Additional context/screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by PaulNewton** [comment]
@liamgriffin Localization - This happens when a locale does not have a `date_formats` property. 
A default install of Dawn 2.0.0-alpha.23  is missing this property in `en.default.json` and other locale definitions.
_[Dev docs - Setting format options in locale files](https://shopify.dev/api/liquid/filters/html-filters#setting-format-options-in-locale-files)_

Fixes:
1. Update a theme to the latest version should fix that as it seems to exist in master for alot of locales ([repo search for date_time](https://github.com/Shopify/dawn/search?p=2&q=date_formats) )
2. adding the following json to a locale for a users theme
```
"date_formats": {
  "month_day_year": "%B %d, %Y"
}
```
3. abstract out date format strings into a snippet for some sort of validation somehow? that defaults somehow?


Unfortunately I don't believe there's a sane inline way to have a **default** based on a localization omission such as this, the following examples are invalid nonsense for several reasons primarily that article.published_at is true so the filter wouldn't default , or the syntax doesn't exist.
~~`{{ article.published_at | time_tag: format: 'month_year' | default: "time_tag: format: 'date'" }}`~~
~~`{{ article.published_at | time_tag: format: 'month_year',default_format:'date' }}`~~

Bigger picture - 
Date formatting is hard, localization is harder, multiplied together they are regressions waiting to happen.
 Better support for coding date logic is also needed upstream in the linter, liquid , and code editor to improve handling situations exactly like this which can be really confusing and thus lead to inflexible fixes instead of improved localization flexibility because a little known property is missing in someones presentation language.

- [ ] Linter - This should probably be a linter warn on locales missing `date_formats` if not already

- [ ]  Liquid - liquid errors should be more clear in what the issue is since locales are supposed to be part of this format parameter but are not included in error checking|messaging creating confusion. At minimum the wording should be improved : 
`Liquid error (snippets/article-card.liquid line 45): the format option 'month_year' is not a supported format` **`or it was not found in your current locale as the value of the optional property: date_time.`** ( bleh: date_time may or may not exist it could just be blank or not have that format so may need to squeeze that fact into the messaging.)
- [ ] Liquid - need a way to default when a localization fails even though the subject variable isn't defaultable either a native default such as a store preference or another new filter option:
 `{{ article.published_at | time_tag: format: 'month_year',` **`default_format:'date'`**  `}}`

 - [ ]  The admin editor should make it easier to validate locales `date_formats` property exists when using date or time format parameters|strings.

References https://shopify.dev/api/liquid/filters/html-filters#time_tag
and the available documented formats https://shopify.dev/api/liquid/filters/html-filters#format

**Comment by PaulNewton** [comment]
> abstract out date format strings into a snippet for some sort of validation somehow? that defaults somehow?

This does make me wonder about the scope of the dawn project and how granular things should go like it can make sense to have a snippet for price display logic, but would it make sense to have a snippet for handling date displays with exposed settings?

**Comment by liamgriffin** [comment]
Closing as this bug is fixed in most recent version of Dawn.
